### Doing
 - [ ] Add CMS_IDs to Outbreaks and Facilities

### To Do
 - [ ] Group Facilities by CMS_Provider_Num WHERE Available
 
### DONE
 - [x] Separate funtions into separate Python files

In [1]:
import pandas as pd
import urllib3 as urllib
import urllib.request as urllib2
import json
import glob
import IPython.display

from Modules.IL_Functions import *

pd.options.display.max_columns = None

## 1 - Get "Raw Data" from website and store in file

In [2]:
[reporting_date, ltc_data] = pull_IL_json_from_web()

In [3]:
# print('Source File: ' + str(json_file))
[reporting_date, summary, outbreak_df, df_facilities, df_county] = process_IL_dict(ltc_data, ltc_name2cms_id, display_dfs=False)

Date: 2021-01-01
Cases: 65078
Deaths: 8297
Outbreaks: 1853
Open Outbreaks: 1025
Closed Outbreaks: 828
Facilities: 1488

In [4]:
outbreak_df.groupby(['County', 'FacilityName']).sum()

                                            confirmed_cases  deaths       CFR  \
County   FacilityName
Adams    Adams Pointe Senior Living                       4       0  0.000000
         Bickford Cottage (2)                             4       0  0.000000
         Bradford Villa                                   8       1  0.125000
         Bradford Villa (2)                              12       0  0.000000
         Cedarhurst                                      26       1  0.038462
...                                                     ...     ...       ...
Woodford Heritage Health El Paso                         46       9  0.195652
         Snyder Village Assisted Living                   4       0  0.000000
         Snyder Village Assisted Living                   2       0  0.000000
         Snyder Village Health Center                    45      10  0.222222
         The Loft Rehabilitation & Nursing                8       0  0.000000

                                            outbreaks  Closed_Outbreaks  \
County   FacilityName
Adams    Adams Pointe Senior Living                 1                 1
         Bickford Cottage (2)                       1                 0
         Bradford Villa                             1                 1
         Bradford Villa (2)                         1                 0
         Cedarhurst                                 1                 1
...                                               ...               ...
Woodford Heritage Health El Paso                    1                 0
         Snyder Village Assisted Living             1                 0
         Snyder Village Assisted Living             1                 1
         Snyder Village Health Center               1                 0
         The Loft Rehabilitation & Nursing          1                 0

                                            Open_Outbreaks
County   FacilityName
Adams    Adams Pointe Senior Living                      0
         Bickford Cottage (2)                            1
         Bradford Villa                                  0
         Bradford Villa (2)                              1
         Cedarhurst                                      0
...                                                    ...
Woodford Heritage Health El Paso                         1
         Snyder Village Assisted Living                  1
         Snyder Village Assisted Living                  0
         Snyder Village Health Center                    1
         The Loft Rehabilitation & Nursing               1

[1510 rows x 6 columns]

In [5]:
df_facilities.sort_values(by='Open_Outbreaks', ascending=False).head(20)

                                                       ReportingDate  \
County    FacilityName2                    CMS_ProvNum
Cook      Franciscan Village               146029         2021-01-01
          Alden North Shore                145984         2021-01-01
Lake      Rolling Hills Manor              145443         2021-01-01
Cook      Citadel of Skokie                145468         2021-01-01
          Symphony of South Shore          145977         2021-01-01
          Symphony of Morgan Park          145764         2021-01-01
          Balmoral Home                    145796         2021-01-01
          Austin Oasis                     145834         2021-01-01
Vermilion Accolade Health Care of Danville No Match       2021-01-01
Cook      Arbour Health Care Center        146169         2021-01-01
          Lakeview Nursing and Rehab       145654         2021-01-01
          SHERIDAN VILLAGE NURSING HOME    No Match       2021-01-01
Macoupin  Carlinville Heritage Health      145456         2021-01-01
Jefferson Heritage Woods                   No Match       2021-01-01
Kane      Bright Oaks of Aurora            No Match       2021-01-01
St. Clair Brightly Senior Living           No Match       2021-01-01
Jackson   Prairie Living at Chautauqua     No Match       2021-01-01
St. Clair Bria of Cahokia                  145613         2021-01-01
Kane      Avantara of Aurora               No Match       2021-01-01
          Avantara of Elgin                145699         2021-01-01

                                                        confirmed_cases  \
County    FacilityName2                    CMS_ProvNum
Cook      Franciscan Village               146029                    54
          Alden North Shore                145984                    14
Lake      Rolling Hills Manor              145443                   122
Cook      Citadel of Skokie                145468                    53
          Symphony of South Shore          145977                   223
          Symphony of Morgan Park          145764                   209
          Balmoral Home                    145796                    49
          Austin Oasis                     145834                   116
Vermilion Accolade Health Care of Danville No Match                  22
Cook      Arbour Health Care Center        146169                    70
          Lakeview Nursing and Rehab       145654                   100
          SHERIDAN VILLAGE NURSING HOME    No Match                   8
Macoupin  Carlinville Heritage Health      145456                    14
Jefferson Heritage Woods                   No Match                   4
Kane      Bright Oaks of Aurora            No Match                  24
St. Clair Brightly Senior Living           No Match                  21
Jackson   Prairie Living at Chautauqua     No Match                  16
St. Clair Bria of Cahokia                  145613                    47
Kane      Avantara of Aurora               No Match                   6
          Avantara of Elgin                145699                    72

                                                        deaths       CFR  \
County    FacilityName2                    CMS_ProvNum
Cook      Franciscan Village               146029            7  0.129630
          Alden North Shore                145984            3  0.214286
Lake      Rolling Hills Manor              145443           19  0.155738
Cook      Citadel of Skokie                145468           14  0.264151
          Symphony of South Shore          145977           32  0.143498
          Symphony of Morgan Park          145764           26  0.124402
          Balmoral Home                    145796            2  0.040816
          Austin Oasis                     145834           16  0.137931
Vermilion Accolade Health Care of Danville No Match          7  0.318182
Cook      Arbour Health Care Center        146169            3  0.042857
          Lakeview Nursing and Rehab       145654           22  0.220000
          SHERIDAN VILLAGE NURSING HOME    No Match          0  0.000000
Macoupin  Carlinville Heritage Health      145456            1  0.071429
Jefferson Heritage Woods                   No Match          0  0.000000
Kane      Bright Oaks of Aurora            No Match          4  0.166667
St. Clair Brightly Senior Living           No Match          3  0.142857
Jackson   Prairie Living at Chautauqua     No Match          1  0.062500
St. Clair Bria of Cahokia                  145613            4  0.085106
Kane      Avantara of Aurora               No Match          0  0.000000
          Avantara of Elgin                145699           15  0.208333

                                                        outbreaks  \
County    FacilityName2                    CMS_ProvNum
Cook      Franciscan Village               146029               2
          Alden North Shore                145984               3
Lake      Rolling Hills Manor              145443               3
Cook      Citadel of Skokie                145468               3
          Symphony of South Shore          145977               2
          Symphony of Morgan Park          145764               2
          Balmoral Home                    145796               2
          Austin Oasis                     145834               2
Vermilion Accolade Health Care of Danville No Match             2
Cook      Arbour Health Care Center        146169               3
          Lakeview Nursing and Rehab       145654               2
          SHERIDAN VILLAGE NURSING HOME    No Match             2
Macoupin  Carlinville Heritage Health      145456               2
Jefferson Heritage Woods                   No Match             1
Kane      Bright Oaks of Aurora            No Match             2
St. Clair Brightly Senior Living           No Match             1
Jackson   Prairie Living at Chautauqua     No Match             1
St. Clair Bria of Cahokia                  145613               2
Kane      Avantara of Aurora               No Match             1
          Avantara of Elgin                145699               1

                                                        Closed_Outbreaks  \
County    FacilityName2                    CMS_ProvNum
Cook      Franciscan Village               146029                      0
          Alden North Shore                145984                      1
Lake      Rolling Hills Manor              145443                      1
Cook      Citadel of Skokie                145468                      1
          Symphony of South Shore          145977                      0
          Symphony of Morgan Park          145764                      0
          Balmoral Home                    145796                      0
          Austin Oasis                     145834                      0
Vermilion Accolade Health Care of Danville No Match                    0
Cook      Arbour Health Care Center        146169                      1
          Lakeview Nursing and Rehab       145654                      0
          SHERIDAN VILLAGE NURSING HOME    No Match                    0
Macoupin  Carlinville Heritage Health      145456                      0
Jefferson Heritage Woods                   No Match                    0
Kane      Bright Oaks of Aurora            No Match                    1
St. Clair Brightly Senior Living           No Match                    0
Jackson   Prairie Living at Chautauqua     No Match                    0
St. Clair Bria of Cahokia                  145613                      1
Kane      Avantara of Aurora               No Match                    0
          Avantara of Elgin                145699                      0

                                                        Open_Outbreaks  \
County    FacilityName2                    CMS_ProvNum
Cook      Franciscan Village               146029                    2
          Alden North Shore                145984                    2
Lake      Rolling Hills Manor              145443                    2
Cook      Citadel of Skokie                145468                    2
          Symphony of South Shore          145977                    2
          Symphony of Morgan Park          145764                    2
          Balmoral Home                    145796                    2
          Austin Oasis                     145834                    2
Vermilion Accolade Health Care of Danville No Match                  2
Cook      Arbour Health Care Center        146169                    2
          Lakeview Nursing and Rehab       145654                    2
          SHERIDAN VILLAGE NURSING HOME    No Match                  2
Macoupin  Carlinville Heritage Health      145456                    2
Jefferson Heritage Woods                   No Match                  1
Kane      Bright Oaks of Aurora            No Match                  1
St. Clair Brightly Senior Living           No Match                  1
Jackson   Prairie Living at Chautauqua     No Match                  1
St. Clair Bria of Cahokia                  145613                    1
Kane      Avantara of Aurora               No Match                  1
          Avantara of Elgin                145699                    1

                                                        facilities
County    FacilityName2                    CMS_ProvNum
Cook      Franciscan Village               146029                1
          Alden North Shore                145984                1
Lake      Rolling Hills Manor              145443                1
Cook      Citadel of Skokie                145468                1
          Symphony of South Shore          145977                1
          Symphony of Morgan Park          145764                1
          Balmoral Home                    145796                1
          Austin Oasis                     145834                1
Vermilion Accolade Health Care of Danville No Match              1
Cook      Arbour Health Care Center        146169                1
          Lakeview Nursing and Rehab       145654                1
          SHERIDAN VILLAGE NURSING HOME    No Match              1
Macoupin  Carlinville Heritage Health      145456                1
Jefferson Heritage Woods                   No Match              1
Kane      Bright Oaks of Aurora            No Match              1
St. Clair Brightly Senior Living           No Match              1
Jackson   Prairie Living at Chautauqua     No Match              1
St. Clair Bria of Cahokia                  145613                1
Kane      Avantara of Aurora               No Match              1
          Avantara of Elgin                145699                1

In [6]:
outbreak_df.head(5)

,reporting_date,County,FacilityName,confirmed_cases,deaths,ReportDate,status,CFR,outbreaks,county-facName,CMS_ProvNum,Closed_Outbreaks,Open_Outbreaks,FacilityName2
0,2021-01-01,Adams,Chaddock,11,0,2021-01-01T00:00:00,Open,0.000000,1,ADAMS-CHADDOCK,No Match,0,1,Chaddock
1,2021-01-01,Adams,Illinois Veterans Home Quincy,239,6,2021-01-01T00:00:00,Open,0.025105,1,ADAMS-ILLINOIS VETERANS HOME QUINCY,No Match,0,1,Illinois Veterans Home Quincy
2,2021-01-01,Adams,Good Samaritan Home,44,1,2021-01-01T00:00:00,Open,0.022727,1,ADAMS-GOOD SAMARITAN HOME,145773,0,1,Good Samaritan Home
3,2021-01-01,Adams,Adams Pointe Senior Living,4,0,2021-01-01T00:00:00,Closed,0.000000,1,ADAMS-ADAMS POINTE SENIOR LIVING,No Match,1,0,Adams Pointe Senior Living
4,2021-01-01,Adams,Bradford Villa,8,1,2021-01-01T00:00:00,Closed,0.125000,1,ADAMS-BRADFORD VILLA,No Match,1,0,Bradford Villa

In [7]:
df_facilities.head(10)

                                                 ReportingDate  \
County FacilityName2                 CMS_ProvNum
Adams  Adams Pointe Senior Living    No Match       2021-01-01
       Bickford Cottage              No Match       2021-01-01
       Bradford Villa                No Match       2021-01-01
       Cedarhurst                    No Match       2021-01-01
       Chaddock                      No Match       2021-01-01
       Golden Good Shepperd Home     No Match       2021-01-01
       Good Samaritan Home           145773         2021-01-01
       Illinois Veterans Home Quincy No Match       2021-01-01
       Quincy Terrace                No Match       2021-01-01
       St Vincents Nursing Home      145457         2021-01-01

                                                  confirmed_cases  deaths  \
County FacilityName2                 CMS_ProvNum
Adams  Adams Pointe Senior Living    No Match                   4       0
       Bickford Cottage              No Match                   4       0
       Bradford Villa                No Match                  20       1
       Cedarhurst                    No Match                  26       1
       Chaddock                      No Match                  11       0
       Golden Good Shepperd Home     No Match                  54       9
       Good Samaritan Home           145773                    44       1
       Illinois Veterans Home Quincy No Match                 239       6
       Quincy Terrace                No Match                  16       1
       St Vincents Nursing Home      145457                   101      17

                                                       CFR  outbreaks  \
County FacilityName2                 CMS_ProvNum
Adams  Adams Pointe Senior Living    No Match     0.000000          1
       Bickford Cottage              No Match     0.000000          1
       Bradford Villa                No Match     0.050000          2
       Cedarhurst                    No Match     0.038462          1
       Chaddock                      No Match     0.000000          1
       Golden Good Shepperd Home     No Match     0.166667          1
       Good Samaritan Home           145773       0.022727          1
       Illinois Veterans Home Quincy No Match     0.025105          1
       Quincy Terrace                No Match     0.062500          1
       St Vincents Nursing Home      145457       0.168317          1

                                                  Closed_Outbreaks  \
County FacilityName2                 CMS_ProvNum
Adams  Adams Pointe Senior Living    No Match                    1
       Bickford Cottage              No Match                    0
       Bradford Villa                No Match                    1
       Cedarhurst                    No Match                    1
       Chaddock                      No Match                    0
       Golden Good Shepperd Home     No Match                    1
       Good Samaritan Home           145773                      0
       Illinois Veterans Home Quincy No Match                    0
       Quincy Terrace                No Match                    0
       St Vincents Nursing Home      145457                      0

                                                  Open_Outbreaks  facilities
County FacilityName2                 CMS_ProvNum
Adams  Adams Pointe Senior Living    No Match                  0           1
       Bickford Cottage              No Match                  1           1
       Bradford Villa                No Match                  1           1
       Cedarhurst                    No Match                  0           1
       Chaddock                      No Match                  1           1
       Golden Good Shepperd Home     No Match                  0           1
       Good Samaritan Home           145773                    1           1
       Illinois Veterans Home Quincy No Match                  1           1
       Quincy Terrace                No Match                  1           1
       St Vincents Nursing Home      145457                    1           1

In [8]:
display(df_facilities.reset_index().head(5))
df_facilities.head(5)

,County,FacilityName2,CMS_ProvNum,ReportingDate,confirmed_cases,deaths,CFR,outbreaks,Closed_Outbreaks,Open_Outbreaks,facilities
0,Adams,Adams Pointe Senior Living,No Match,2021-01-01,4,0,0.000000,1,1,0,1
1,Adams,Bickford Cottage,No Match,2021-01-01,4,0,0.000000,1,0,1,1
2,Adams,Bradford Villa,No Match,2021-01-01,20,1,0.050000,2,1,1,1
3,Adams,Cedarhurst,No Match,2021-01-01,26,1,0.038462,1,1,0,1
4,Adams,Chaddock,No Match,2021-01-01,11,0,0.000000,1,0,1,1

                                              ReportingDate  confirmed_cases  \
County FacilityName2              CMS_ProvNum
Adams  Adams Pointe Senior Living No Match       2021-01-01                4
       Bickford Cottage           No Match       2021-01-01                4
       Bradford Villa             No Match       2021-01-01               20
       Cedarhurst                 No Match       2021-01-01               26
       Chaddock                   No Match       2021-01-01               11

                                               deaths       CFR  outbreaks  \
County FacilityName2              CMS_ProvNum
Adams  Adams Pointe Senior Living No Match          0  0.000000          1
       Bickford Cottage           No Match          0  0.000000          1
       Bradford Villa             No Match          1  0.050000          2
       Cedarhurst                 No Match          1  0.038462          1
       Chaddock                   No Match          0  0.000000          1

                                               Closed_Outbreaks  \
County FacilityName2              CMS_ProvNum
Adams  Adams Pointe Senior Living No Match                    1
       Bickford Cottage           No Match                    0
       Bradford Villa             No Match                    1
       Cedarhurst                 No Match                    1
       Chaddock                   No Match                    0

                                               Open_Outbreaks  facilities
County FacilityName2              CMS_ProvNum
Adams  Adams Pointe Senior Living No Match                  0           1
       Bickford Cottage           No Match                  1           1
       Bradford Villa             No Match                  1           1
       Cedarhurst                 No Match                  0           1
       Chaddock                   No Match                  1           1

In [9]:
df_facilities.reset_index().groupby(['CMS_ProvNum']).count().sort_values(by='County', ascending=False)

,County,FacilityName2,ReportingDate,confirmed_cases,deaths,CFR,outbreaks,Closed_Outbreaks,Open_Outbreaks,facilities
CMS_ProvNum,,,,,,,,,,
No Match,941,941,941,941,941,941,941,941,941,941
145364,3,3,3,3,3,3,3,3,3,3
14E888,2,2,2,2,2,2,2,2,2,2
145609,2,2,2,2,2,2,2,2,2,2
145784,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...
145639,1,1,1,1,1,1,1,1,1,1
145638,1,1,1,1,1,1,1,1,1,1
145637,1,1,1,1,1,1,1,1,1,1
145636,1,1,1,1,1,1,1,1,1,1
140E170,1,1,1,1,1,1,1,1,1,1

In [10]:
df_facilities = df_facilities.reset_index()
s = df_facilities.CMS_ProvNum.value_counts()
dupNamesList = list(s.where((s > 1) & (s < 100)).dropna().keys())

In [11]:
s = df_facilities.CMS_ProvNum.value_counts()
dupNamesList = list(s.where((s > 1) & (s < 100)).dropna().keys())

In [12]:
dupFacNames_df = df_facilities[df_facilities['CMS_ProvNum'].isin(dupNamesList)].sort_values(by='CMS_ProvNum')
dupFacNames_df.to_csv('IL_dup_fac_names.csv')
dupFacNames_df

,County,FacilityName2,CMS_ProvNum,ReportingDate,confirmed_cases,deaths,CFR,outbreaks,Closed_Outbreaks,Open_Outbreaks,facilities
767,Kane,The Grove Fox Valley,145006,2021-01-01,168,21,0.125000,2,1,1,1
769,Kane,The Grove of Fox Valley,145006,2021-01-01,7,0,0.000000,1,1,0,1
779,Kankakee,Citadel Care Center of Kankakee,145043,2021-01-01,5,0,0.000000,1,0,1,1
780,Kankakee,Citadel of Kankakee,145043,2021-01-01,80,2,0.025000,1,0,1,1
1046,McHenry,Cross Roads Care Center,145222,2021-01-01,71,13,0.183099,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...
324,Cook,Little Sisters of the Poor/St. Marys Home,146185,2021-01-01,61,13,0.213115,1,1,0,1
710,Kane,Alden Estates Courts of Huntley,146186,2021-01-01,9,0,0.000000,1,1,0,1
711,Kane,Alden Estates-Courts of Huntley,146186,2021-01-01,48,2,0.041667,1,0,1,1
1153,Peoria,Sharon Healthcare Willows,14E888,2021-01-01,100,2,0.020000,1,0,1,1
1154,Peoria,Sharon Healthcare Willows South,14E888,2021-01-01,4,1,0.250000,1,1,0,1

# Convert Facility Sheet to CTP format

In [13]:
CTP_cols = ['ReportingDate', 'State', 'County', 
            'City',
            'FacilityName', 'TYPE',
            'CTP Facility Categorization',
            'State/Fed Regulated',
            'State Facility ID',
            'CMS Facility ID',
            'Date outbreak opened', 'Date outreak closed', 'Outbreak Status','Resident Census',
            
'TOTAL RESIDENT CASES', # 'Resident Positives ',
          'TOTAL Resident Probable Positives',
'TOTAL RESIDENT DEATHS', # 'Resident Deaths',
         'TOTAL Resident Probable Deaths',
'TOTAL STAFF CASES', #'Staff Positive',
         'TOTAL Staff Probable Positives',
'TOTAL STAFF DEATHS', #'TOTAL Staff Deaths',
         'TOTAL Staff Probable Deaths',
 'confirmed_cases',
 'TOTAL Resident/Staff Probable Positives',
 'deaths',
 'TOTAL Resident/Staff Probable Deaths',
 
'NEW RESIDENT CASES', #            'Resident Positives',
     'NEW Resident Probable Positives',
 'NEW RESIDENT DEATHS',
     'NEW Resident Probable Deaths',
 'NEW STAFF CASES',
     'NEW Staff Probable Positives',
 'NEW STAFF DEATHS',
     'NEW Staff Probable Deaths',
 'NEW Resident/Staff Positives',
 'NEW Resident/Staff Probable Positives',
 'NEW Resident/Staff Deaths',
 'NEW Resident/Staff Probable Deaths',
 'Residents Tested',
 'Staff Tested',
 'Personal Protective Equipment',
           'COMPLIANCE']

CTP_Blank_Cols = ['City',
             'TYPE',
            'CTP Facility Categorization',
            'State/Fed Regulated',
            'State Facility ID',
            'CMS Facility ID',
            'Date outbreak opened', 'Date outreak closed', 'Resident Census',
            
'TOTAL RESIDENT CASES', # 'Resident Positives ',
          'TOTAL Resident Probable Positives',
'TOTAL RESIDENT DEATHS', # 'Resident Deaths',
         'TOTAL Resident Probable Deaths',
'TOTAL STAFF CASES', #'Staff Positive',
         'TOTAL Staff Probable Positives',
'TOTAL STAFF DEATHS', #'TOTAL Staff Deaths',
         'TOTAL Staff Probable Deaths',

 'TOTAL Resident/Staff Probable Positives',

 'TOTAL Resident/Staff Probable Deaths',
 
'NEW RESIDENT CASES', #            'Resident Positives',
     'NEW Resident Probable Positives',
 'NEW RESIDENT DEATHS',
     'NEW Resident Probable Deaths',
 'NEW STAFF CASES',
     'NEW Staff Probable Positives',
 'NEW STAFF DEATHS',
     'NEW Staff Probable Deaths',
 'NEW Resident/Staff Positives',
 'NEW Resident/Staff Probable Positives',
 'NEW Resident/Staff Deaths',
 'NEW Resident/Staff Probable Deaths',
 'Residents Tested',
 'Staff Tested',
 'Personal Protective Equipment',
           'COMPLIANCE']

In [14]:
def open_closed(outbreaks):
    if outbreaks == 0:
        return 'Closed'
    else:
        return 'Open'
        
for col in CTP_Blank_Cols:
    df_facilities[col] = ''
df_facilities['Outbreak Status'] = df_facilities['Open_Outbreaks'].apply(open_closed) #TO FINISH
df_facilities['State'] = 'IL'
df_facilities['ReportingDate'] = reporting_date.replace('-', '')

In [15]:
df_facilities.rename(columns={'FacilityName2': 'FacilityName'}, inplace=True)
df_facilities[CTP_cols].to_csv('Reporting_data/IL_' + reporting_date + '_Facilities_LTC_data_vCTP.csv', index=False)

In [16]:
df_facilities.columns

Index(['County', 'FacilityName', 'CMS_ProvNum', 'ReportingDate',
       'confirmed_cases', 'deaths', 'CFR', 'outbreaks', 'Closed_Outbreaks',
       'Open_Outbreaks', 'facilities', 'City', 'TYPE',
       'CTP Facility Categorization', 'State/Fed Regulated',
       'State Facility ID', 'CMS Facility ID', 'Date outbreak opened',
       'Date outreak closed', 'Resident Census', 'TOTAL RESIDENT CASES',
       'TOTAL Resident Probable Positives', 'TOTAL RESIDENT DEATHS',
       'TOTAL Resident Probable Deaths', 'TOTAL STAFF CASES',
       'TOTAL Staff Probable Positives', 'TOTAL STAFF DEATHS',
       'TOTAL Staff Probable Deaths',
       'TOTAL Resident/Staff Probable Positives',
       'TOTAL Resident/Staff Probable Deaths', 'NEW RESIDENT CASES',
       'NEW Resident Probable Positives', 'NEW RESIDENT DEATHS',
       'NEW Resident Probable Deaths', 'NEW STAFF CASES',
       'NEW Staff Probable Positives', 'NEW STAFF DEATHS',
       'NEW Staff Probable Deaths', 'NEW Resident/Staff Positives',
       'NEW Resident/Staff Probable Positives', 'NEW Resident/Staff Deaths',
       'NEW Resident/Staff Probable Deaths', 'Residents Tested',
       'Staff Tested', 'Personal Protective Equipment', 'COMPLIANCE',
       'Outbreak Status', 'State'],
      dtype='object')

In [17]:
df_facilities

,County,FacilityName,CMS_ProvNum,ReportingDate,confirmed_cases,deaths,CFR,outbreaks,Closed_Outbreaks,Open_Outbreaks,facilities,City,TYPE,CTP Facility Categorization,State/Fed Regulated,State Facility ID,CMS Facility ID,Date outbreak opened,Date outreak closed,Resident Census,TOTAL RESIDENT CASES,TOTAL Resident Probable Positives,TOTAL RESIDENT DEATHS,TOTAL Resident Probable Deaths,TOTAL STAFF CASES,TOTAL Staff Probable Positives,TOTAL STAFF DEATHS,TOTAL Staff Probable Deaths,TOTAL Resident/Staff Probable Positives,TOTAL Resident/Staff Probable Deaths,NEW RESIDENT CASES,NEW Resident Probable Positives,NEW RESIDENT DEATHS,NEW Resident Probable Deaths,NEW STAFF CASES,NEW Staff Probable Positives,NEW STAFF DEATHS,NEW Staff Probable Deaths,NEW Resident/Staff Positives,NEW Resident/Staff Probable Positives,NEW Resident/Staff Deaths,NEW Resident/Staff Probable Deaths,Residents Tested,Staff Tested,Personal Protective Equipment,COMPLIANCE,Outbreak Status,State
0,Adams,Adams Pointe Senior Living,No Match,20210101,4,0,0.000000,1,1,0,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Closed,IL
1,Adams,Bickford Cottage,No Match,20210101,4,0,0.000000,1,0,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Open,IL
2,Adams,Bradford Villa,No Match,20210101,20,1,0.050000,2,1,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Open,IL
3,Adams,Cedarhurst,No Match,20210101,26,1,0.038462,1,1,0,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Closed,IL
4,Adams,Chaddock,No Match,20210101,11,0,0.000000,1,0,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Open,IL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1483,Woodford,El Paso Health Care Center,No Match,20210101,75,0,0.000000,1,0,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Open,IL
1484,Woodford,Heritage Health El Paso,145319,20210101,46,9,0.195652,1,0,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Open,IL
1485,Woodford,Snyder Village Assisted Living,145596,20210101,6,0,0.000000,2,1,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Open,IL
1486,Woodford,Snyder Village Health Center,No Match,20210101,45,10,0.222222,1,0,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Open,IL
1487,Woodford,The Loft Rehabilitation & Nursing,No Match,20210101,8,0,0.000000,1,0,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Open,IL

# Play Area

In [18]:
this_week_df = pd.read_csv('Reporting_data/IL_' + reporting_date + '_Facilities_LTC_data_v4.csv')

In [19]:
last_week_df= pd.read_csv('Reporting_data/IL_' + '2020-12-11' + '_Facilities_LTC_data_v4.csv')

In [20]:
new_df = pd.merge(this_week_df, last_week_df,  how='left', on=['County', 'FacilityName'])

KeyError: 'FacilityName'

In [ ]:
new_df['new_cases']= new_df['confirmed_cases_x'] - new_df['confirmed_cases_y']
new_df['new_deaths']= new_df['deaths_x'] - new_df['deaths_y']

In [ ]:
new_df.columns

In [ ]:
cols=['County', 'FacilityName', 'CMS_ProvNum_x',
       'confirmed_cases_x', 'deaths_x', 'confirmed_cases_y', 'deaths_y', 'new_cases', 'new_deaths']
new_df[cols].sort_values(by='new_cases', ascending=False).head(10)

In [ ]:
new_df[cols].sort_values(by='new_deaths', ascending=False).head(10)

In [ ]:
import re
regex = re.compile('\(\d\)')
a = 'adsds (3)'
regex.split(a)[0].strip()

In [ ]:
regex.split(a)[0].strip

In [ ]:
outbreak_df

In [ ]:
# outbreak_df['Closed_Outbreaks'] = outbreak_df['status'].apply(lambda x: 1 if x == "Closed" else 0)
# outbreak_df['Open_Outbreaks'] = outbreak_df['status'].apply(lambda x: 1 if x == "Open" else 0)


# # V2 - Remove cases of duplicate Outbreaks where they append (#) to end of Facility name to allow proper aggregation at the facility level
# regex = re.compile('\(\d\)')
# outbreak_df['FacilityName2'] = outbreak_df['FacilityName'].apply(lambda x: regex.split(x)[0].strip())


# # Save and Display Facility data
# df_facilities = outbreak_df.groupby(['County', 'FacilityName2', 'CMS_ProvNum']).sum()

In [ ]:
# a = df_facilities.sort_values(by=['FacilityName2'])

In [ ]:
# a[350:400]

In [ ]:
summary