In [74]:
import pandas as pd
import json
import glob
import IPython.display
import altair as alt

pd.options.display.max_columns = None

In [3]:
for file in glob.glob('Source_data/IL_*LTC_data_Source.json'):
    print(file)

Source_data/IL_2020-10-30LTC_data_Source.json
Source_data/IL_2020-07-10LTC_data_Source.json
Source_data/IL_2020-11-06_LTC_data_Source.json
Source_data/IL_2020-06-05LTC_data_Source.json
Source_data/IL_2020-09-11LTC_data_Source.json
Source_data/IL_2020-06-19LTC_data_Source.json
Source_data/IL_2020-07-17LTC_data_Source.json
Source_data/IL_2020-08-07LTC_data_Source.json
Source_data/IL_2020-10-23LTC_data_Source.json
Source_data/IL_2020-07-03LTC_data_Source.json
Source_data/IL_2020-12-11_LTC_data_Source.json
Source_data/IL_2021-01-08_LTC_data_Source.json
Source_data/IL_2020-09-04LTC_data_Source.json
Source_data/IL_2020-06-12LTC_data_Source.json
Source_data/IL_2021-01-15_LTC_data_Source.json
Source_data/IL_2020-08-14LTC_data_Source.json
Source_data/IL_2020-11-27_LTC_data_Source.json
Source_data/IL_2020-09-18LTC_data_Source.json
Source_data/IL_2020-11-13_LTC_data_Source.json
Source_data/IL_2020-10-16LTC_data_Source.json
Source_data/IL_2021-01-01_LTC_data_Source.json
Source_data/IL_2020-07-31LTC_data_Source.json
Source_data/IL_2020-12-18_LTC_data_Source.json
Source_data/IL_2020-12-25_LTC_data_Source.json
Source_data/IL_2020-10-09LTC_data_Source.json
Source_data/IL_2020-08-21LTC_data_Source.json
Source_data/IL_2020-06-26LTC_data_Source.json
Source_data/IL_2020-11-20_LTC_data_Source.json
Source_data/IL_2020-12-04_LTC_data_Source.json
Source_data/IL_2020-07-24LTC_data_Source.json
Source_data/IL_2020-05-29LTC_data_Source.json
Source_data/IL_2020-10-02LTC_data_Source.json
Source_data/IL_2020-09-25LTC_data_Source.json
Source_data/IL_2020-08-28LTC_data_Source.json

In [15]:

with open('Source_data/IL_2021-01-15_LTC_data_Source.json') as fp:
    data = fp.read()
    jsonData = json.loads(data)

In [105]:
df = pd.DataFrame(jsonData['LTC_Historical_Reported_Cases'])
df.sort_values(by=['reported_date'], inplace=True)
df['new_deaths']= df.deaths.diff()
df['new_confirmed_cases'] = df.confirmed_cases.diff()

In [109]:
chart_title = ' Cases by Week'
chart1 = alt.Chart(df).mark_bar().encode(
                     x='reported_date:O',
                     y='new_confirmed_cases',
                     ).properties( width=400, height=400, title=chart_title)
chart1

alt.Chart(...)

In [103]:
df

,confirmed_cases,deaths,reported_date,new_deaths,new_confirmed_cases
34,14882,2402,2020-05-23T00:00:00,NaN,NaN
33,17098,2744,2020-05-29T00:00:00,342.0,2216.0
32,18840,3144,2020-06-05T00:00:00,400.0,1742.0
31,20550,3433,2020-06-12T00:00:00,289.0,1710.0
30,21390,3649,2020-06-19T00:00:00,216.0,840.0
29,22170,3772,2020-06-26T00:00:00,123.0,780.0
28,22833,3856,2020-07-03T00:00:00,84.0,663.0
27,23324,3895,2020-07-10T00:00:00,39.0,491.0
26,23607,3974,2020-07-17T00:00:00,79.0,283.0
25,24106,4062,2020-07-24T00:00:00,88.0,499.0
24,24845,4136,2020-07-31T00:00:00,74.0,739.0
23,25448,4162,2020-08-07T00:00:00,26.0,603.0
22,25869,4298,2020-08-14T00:00:00,136.0,421.0
21,26357,4319,2020-08-21T00:00:00,21.0,488.0
20,27126,4396,2020-08-28T00:00:00,77.0,769.0
19,27738,4445,2020-09-04T00:00:00,49.0,612.0
18,28189,4515,2020-09-11T00:00:00,70.0,451.0
17,28941,4575,2020-09-18T00:00:00,60.0,752.0
16,29517,4642,2020-09-25T00:00:00,67.0,576.0
15,30243,4697,2020-10-02T00:00:00,55.0,726.0
14,30920,4792,2020-10-09T00:00:00,95.0,677.0
13,31995,4888,2020-10-16T00:00:00,96.0,1075.0
12,33440,5019,2020-10-23T00:00:00,131.0,1445.0
11,34278,5127,2020-10-30T00:00:00,108.0,838.0
10,36683,5253,2020-11-06T00:00:00,126.0,2405.0
9,39686,5493,2020-11-13T00:00:00,240.0,3003.0
8,43222,5780,2020-11-20T00:00:00,287.0,3536.0
7,45882,6047,2020-11-27T00:00:00,267.0,2660.0
6,50418,6526,2020-12-04T00:00:00,479.0,4536.0
5,54907,6954,2020-12-11T00:00:00,428.0,4489.0
4,59970,7559,2020-12-18T00:00:00,605.0,5063.0
3,62600,7910,2020-12-25T00:00:00,351.0,2630.0
2,65078,8297,2021-01-01T00:00:00,387.0,2478.0
1,67407,8670,2021-01-08T00:00:00,373.0,2329.0
0,69398,8986,2021-01-15T00:00:00,316.0,1991.0

In [64]:
df['NewConfirmedCases'] = df.groupby(['reported_date'])['confirmed_cases'].apply(lambda x: x + x.shift(1))

In [65]:
df

    confirmed_cases  deaths        reported_date  NewConfirmedCases
34            14882    2402  2020-05-23T00:00:00                NaN
33            17098    2744  2020-05-29T00:00:00                NaN
32            18840    3144  2020-06-05T00:00:00                NaN
31            20550    3433  2020-06-12T00:00:00                NaN
30            21390    3649  2020-06-19T00:00:00                NaN
29            22170    3772  2020-06-26T00:00:00                NaN
28            22833    3856  2020-07-03T00:00:00                NaN
27            23324    3895  2020-07-10T00:00:00                NaN
26            23607    3974  2020-07-17T00:00:00                NaN
25            24106    4062  2020-07-24T00:00:00                NaN
24            24845    4136  2020-07-31T00:00:00                NaN
23            25448    4162  2020-08-07T00:00:00                NaN
22            25869    4298  2020-08-14T00:00:00                NaN
21            26357    4319  2020-08-21T00:00:00                NaN
20            27126    4396  2020-08-28T00:00:00                NaN
19            27738    4445  2020-09-04T00:00:00                NaN
18            28189    4515  2020-09-11T00:00:00                NaN
17            28941    4575  2020-09-18T00:00:00                NaN
16            29517    4642  2020-09-25T00:00:00                NaN
15            30243    4697  2020-10-02T00:00:00                NaN
14            30920    4792  2020-10-09T00:00:00                NaN
13            31995    4888  2020-10-16T00:00:00                NaN
12            33440    5019  2020-10-23T00:00:00                NaN
11            34278    5127  2020-10-30T00:00:00                NaN
10            36683    5253  2020-11-06T00:00:00                NaN
9             39686    5493  2020-11-13T00:00:00                NaN
8             43222    5780  2020-11-20T00:00:00                NaN
7             45882    6047  2020-11-27T00:00:00                NaN
6             50418    6526  2020-12-04T00:00:00                NaN
5             54907    6954  2020-12-11T00:00:00                NaN
4             59970    7559  2020-12-18T00:00:00                NaN
3             62600    7910  2020-12-25T00:00:00                NaN
2             65078    8297  2021-01-01T00:00:00                NaN
1             67407    8670  2021-01-08T00:00:00                NaN
0             69398    8986  2021-01-15T00:00:00                NaN

In [40]:
df.columns

Index(['confirmed_cases', 'deaths'], dtype='object')