### Doing
 - [ ] Add CMS_IDs to Outbreaks and Facilities

### To Do
 - [ ] Group Facilities by CMS_Provider_Num WHERE Available
 
### DONE
 - [x] Separate funtions into separate Python files

In [1]:
import pandas as pd
import urllib3 as urllib
import urllib.request as urllib2
import json
import glob
import IPython.display
import altair as alt

from Modules.IL_Functions import *

pd.options.display.max_columns = None

## 1 - Get "Raw Data" from website and store in file

In [2]:
[reporting_date, ltc_data] = pull_IL_json_from_web()

In [3]:
# print('Source File: ' + str(json_file))
[reporting_date, summary, outbreak_df, df_facilities, df_county] = process_IL_dict(ltc_data, ltc_name2cms_id, display_dfs=False)

Date: 2021-01-22
Cases: 71103
Deaths: 9263
Outbreaks: 1950
Open Outbreaks: 1003
Closed Outbreaks: 947
Facilities: 1537

In [4]:
# outbreak_df.groupby(['County', 'FacilityName']).sum()

In [5]:
df_facilities.sort_values(by='Open_Outbreaks', ascending=False).head(20)

                                                       ReportingDate  \
County    FacilityName2                    CMS_ProvNum
Cook      Symphony of South Shore          145977         2021-01-22
          Aperion Care West Ridge          145832         2021-01-22
          Arbour Health Care Center        146169         2021-01-22
          Symphony of Morgan Park          145764         2021-01-22
Lake      Rolling Hills Manor              145443         2021-01-22
Cook      SHERIDAN VILLAGE NURSING HOME    No Match       2021-01-22
          Lakeview Nursing and Rehab       145654         2021-01-22
          Alden North Shore                145984         2021-01-22
          Citadel of Skokie                145468         2021-01-22
          Austin Oasis                     145834         2021-01-22
Vermilion Accolade Health Care of Danville No Match       2021-01-22
Cook      Balmoral Home                    145796         2021-01-22
Lake      The Grove at the Lake            No Match       2021-01-22
          Thrive of Lake County            145460         2021-01-22
          The Wellshire of Lincolnshire    No Match       2021-01-22
          The Solana Deer Park             No Match       2021-01-22
          Sunrise of Highland Park         No Match       2021-01-22
          The Auberge at Highland Park     No Match       2021-01-22
          Terrace Nursing Home             No Match       2021-01-22
          Symphony of Buffalo Grove        145819         2021-01-22

                                                        confirmed_cases  \
County    FacilityName2                    CMS_ProvNum
Cook      Symphony of South Shore          145977                   230
          Aperion Care West Ridge          145832                    68
          Arbour Health Care Center        146169                    89
          Symphony of Morgan Park          145764                   213
Lake      Rolling Hills Manor              145443                   123
Cook      SHERIDAN VILLAGE NURSING HOME    No Match                  10
          Lakeview Nursing and Rehab       145654                   100
          Alden North Shore                145984                    14
          Citadel of Skokie                145468                    53
          Austin Oasis                     145834                   116
Vermilion Accolade Health Care of Danville No Match                  22
Cook      Balmoral Home                    145796                    60
Lake      The Grove at the Lake            No Match                  15
          Thrive of Lake County            145460                    85
          The Wellshire of Lincolnshire    No Match                   2
          The Solana Deer Park             No Match                  58
          Sunrise of Highland Park         No Match                  60
          The Auberge at Highland Park     No Match                   6
          Terrace Nursing Home             No Match                  59
          Symphony of Buffalo Grove        145819                    36

                                                        deaths       CFR  \
County    FacilityName2                    CMS_ProvNum
Cook      Symphony of South Shore          145977           35  0.152174
          Aperion Care West Ridge          145832           14  0.205882
          Arbour Health Care Center        146169            3  0.033708
          Symphony of Morgan Park          145764           26  0.122066
Lake      Rolling Hills Manor              145443           23  0.186992
Cook      SHERIDAN VILLAGE NURSING HOME    No Match          0  0.000000
          Lakeview Nursing and Rehab       145654           22  0.220000
          Alden North Shore                145984            3  0.214286
          Citadel of Skokie                145468           14  0.264151
          Austin Oasis                     145834           16  0.137931
Vermilion Accolade Health Care of Danville No Match          9  0.409091
Cook      Balmoral Home                    145796            6  0.100000
Lake      The Grove at the Lake            No Match          1  0.066667
          Thrive of Lake County            145460            8  0.094118
          The Wellshire of Lincolnshire    No Match          0  0.000000
          The Solana Deer Park             No Match          9  0.155172
          Sunrise of Highland Park         No Match          7  0.116667
          The Auberge at Highland Park     No Match          1  0.166667
          Terrace Nursing Home             No Match         16  0.271186
          Symphony of Buffalo Grove        145819            3  0.083333

                                                        outbreaks  \
County    FacilityName2                    CMS_ProvNum
Cook      Symphony of South Shore          145977               2
          Aperion Care West Ridge          145832               3
          Arbour Health Care Center        146169               3
          Symphony of Morgan Park          145764               2
Lake      Rolling Hills Manor              145443               3
Cook      SHERIDAN VILLAGE NURSING HOME    No Match             2
          Lakeview Nursing and Rehab       145654               2
          Alden North Shore                145984               3
          Citadel of Skokie                145468               3
          Austin Oasis                     145834               2
Vermilion Accolade Health Care of Danville No Match             2
Cook      Balmoral Home                    145796               2
Lake      The Grove at the Lake            No Match             1
          Thrive of Lake County            145460               1
          The Wellshire of Lincolnshire    No Match             1
          The Solana Deer Park             No Match             2
          Sunrise of Highland Park         No Match             1
          The Auberge at Highland Park     No Match             1
          Terrace Nursing Home             No Match             2
          Symphony of Buffalo Grove        145819               1

                                                        Closed_Outbreaks  \
County    FacilityName2                    CMS_ProvNum
Cook      Symphony of South Shore          145977                      0
          Aperion Care West Ridge          145832                      1
          Arbour Health Care Center        146169                      1
          Symphony of Morgan Park          145764                      0
Lake      Rolling Hills Manor              145443                      1
Cook      SHERIDAN VILLAGE NURSING HOME    No Match                    0
          Lakeview Nursing and Rehab       145654                      0
          Alden North Shore                145984                      1
          Citadel of Skokie                145468                      1
          Austin Oasis                     145834                      0
Vermilion Accolade Health Care of Danville No Match                    0
Cook      Balmoral Home                    145796                      0
Lake      The Grove at the Lake            No Match                    0
          Thrive of Lake County            145460                      0
          The Wellshire of Lincolnshire    No Match                    0
          The Solana Deer Park             No Match                    1
          Sunrise of Highland Park         No Match                    0
          The Auberge at Highland Park     No Match                    0
          Terrace Nursing Home             No Match                    1
          Symphony of Buffalo Grove        145819                      0

                                                        Open_Outbreaks  \
County    FacilityName2                    CMS_ProvNum
Cook      Symphony of South Shore          145977                    2
          Aperion Care West Ridge          145832                    2
          Arbour Health Care Center        146169                    2
          Symphony of Morgan Park          145764                    2
Lake      Rolling Hills Manor              145443                    2
Cook      SHERIDAN VILLAGE NURSING HOME    No Match                  2
          Lakeview Nursing and Rehab       145654                    2
          Alden North Shore                145984                    2
          Citadel of Skokie                145468                    2
          Austin Oasis                     145834                    2
Vermilion Accolade Health Care of Danville No Match                  2
Cook      Balmoral Home                    145796                    2
Lake      The Grove at the Lake            No Match                  1
          Thrive of Lake County            145460                    1
          The Wellshire of Lincolnshire    No Match                  1
          The Solana Deer Park             No Match                  1
          Sunrise of Highland Park         No Match                  1
          The Auberge at Highland Park     No Match                  1
          Terrace Nursing Home             No Match                  1
          Symphony of Buffalo Grove        145819                    1

                                                        facilities
County    FacilityName2                    CMS_ProvNum
Cook      Symphony of South Shore          145977                1
          Aperion Care West Ridge          145832                1
          Arbour Health Care Center        146169                1
          Symphony of Morgan Park          145764                1
Lake      Rolling Hills Manor              145443                1
Cook      SHERIDAN VILLAGE NURSING HOME    No Match              1
          Lakeview Nursing and Rehab       145654                1
          Alden North Shore                145984                1
          Citadel of Skokie                145468                1
          Austin Oasis                     145834                1
Vermilion Accolade Health Care of Danville No Match              1
Cook      Balmoral Home                    145796                1
Lake      The Grove at the Lake            No Match              1
          Thrive of Lake County            145460                1
          The Wellshire of Lincolnshire    No Match              1
          The Solana Deer Park             No Match              1
          Sunrise of Highland Park         No Match              1
          The Auberge at Highland Park     No Match              1
          Terrace Nursing Home             No Match              1
          Symphony of Buffalo Grove        145819                1

In [6]:
outbreak_df.head(5)

,reporting_date,County,FacilityName,confirmed_cases,deaths,ReportDate,status,CFR,outbreaks,county-facName,CMS_ProvNum,Closed_Outbreaks,Open_Outbreaks,FacilityName2
0,2021-01-22,Adams,Chaddock,11,0,2021-01-22T00:00:00,Open,0.000000,1,ADAMS-CHADDOCK,No Match,0,1,Chaddock
1,2021-01-22,Adams,Illinois Veterans Home Quincy,239,19,2021-01-22T00:00:00,Open,0.079498,1,ADAMS-ILLINOIS VETERANS HOME QUINCY,No Match,0,1,Illinois Veterans Home Quincy
2,2021-01-22,Adams,Good Samaritan Home,61,4,2021-01-22T00:00:00,Open,0.065574,1,ADAMS-GOOD SAMARITAN HOME,145773,0,1,Good Samaritan Home
3,2021-01-22,Adams,Adams Pointe Senior Living,4,0,2021-01-22T00:00:00,Closed,0.000000,1,ADAMS-ADAMS POINTE SENIOR LIVING,No Match,1,0,Adams Pointe Senior Living
4,2021-01-22,Adams,Bradford Villa,8,1,2021-01-22T00:00:00,Closed,0.125000,1,ADAMS-BRADFORD VILLA,No Match,1,0,Bradford Villa

In [7]:
df_facilities.head(10)

                                                 ReportingDate  \
County FacilityName2                 CMS_ProvNum
Adams  Adams Pointe Senior Living    No Match       2021-01-22
       Bickford Cottage              No Match       2021-01-22
       Blessing Hospital SNU         No Match       2021-01-22
       Bradford Villa                No Match       2021-01-22
       Cedarhurst                    No Match       2021-01-22
       Chaddock                      No Match       2021-01-22
       Curtis Creek                  No Match       2021-01-22
       Golden Good Shepperd Home     No Match       2021-01-22
       Good Samaritan Home           145773         2021-01-22
       Illinois Veterans Home Quincy No Match       2021-01-22

                                                  confirmed_cases  deaths  \
County FacilityName2                 CMS_ProvNum
Adams  Adams Pointe Senior Living    No Match                   4       0
       Bickford Cottage              No Match                   8       0
       Blessing Hospital SNU         No Match                   6       1
       Bradford Villa                No Match                  21       2
       Cedarhurst                    No Match                  26       1
       Chaddock                      No Match                  11       0
       Curtis Creek                  No Match                   6       0
       Golden Good Shepperd Home     No Match                  54       9
       Good Samaritan Home           145773                    61       4
       Illinois Veterans Home Quincy No Match                 239      19

                                                       CFR  outbreaks  \
County FacilityName2                 CMS_ProvNum
Adams  Adams Pointe Senior Living    No Match     0.000000          1
       Bickford Cottage              No Match     0.000000          1
       Blessing Hospital SNU         No Match     0.166667          1
       Bradford Villa                No Match     0.095238          2
       Cedarhurst                    No Match     0.038462          1
       Chaddock                      No Match     0.000000          1
       Curtis Creek                  No Match     0.000000          1
       Golden Good Shepperd Home     No Match     0.166667          1
       Good Samaritan Home           145773       0.065574          1
       Illinois Veterans Home Quincy No Match     0.079498          1

                                                  Closed_Outbreaks  \
County FacilityName2                 CMS_ProvNum
Adams  Adams Pointe Senior Living    No Match                    1
       Bickford Cottage              No Match                    0
       Blessing Hospital SNU         No Match                    0
       Bradford Villa                No Match                    1
       Cedarhurst                    No Match                    1
       Chaddock                      No Match                    0
       Curtis Creek                  No Match                    0
       Golden Good Shepperd Home     No Match                    1
       Good Samaritan Home           145773                      0
       Illinois Veterans Home Quincy No Match                    0

                                                  Open_Outbreaks  facilities
County FacilityName2                 CMS_ProvNum
Adams  Adams Pointe Senior Living    No Match                  0           1
       Bickford Cottage              No Match                  1           1
       Blessing Hospital SNU         No Match                  1           1
       Bradford Villa                No Match                  1           1
       Cedarhurst                    No Match                  0           1
       Chaddock                      No Match                  1           1
       Curtis Creek                  No Match                  1           1
       Golden Good Shepperd Home     No Match                  0           1
       Good Samaritan Home           145773                    1           1
       Illinois Veterans Home Quincy No Match                  1           1

In [8]:
# # display(df_facilities.reset_index().head(5))
# df_facilities.head(5)

In [9]:
df_facilities.reset_index().groupby(['CMS_ProvNum']).count().sort_values(by='County', ascending=False)

,County,FacilityName2,ReportingDate,confirmed_cases,deaths,CFR,outbreaks,Closed_Outbreaks,Open_Outbreaks,facilities
CMS_ProvNum,,,,,,,,,,
No Match,991,991,991,991,991,991,991,991,991,991
145364,3,3,3,3,3,3,3,3,3,3
14E888,2,2,2,2,2,2,2,2,2,2
145609,2,2,2,2,2,2,2,2,2,2
145784,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...
145639,1,1,1,1,1,1,1,1,1,1
145638,1,1,1,1,1,1,1,1,1,1
145637,1,1,1,1,1,1,1,1,1,1
145636,1,1,1,1,1,1,1,1,1,1
140E170,1,1,1,1,1,1,1,1,1,1

In [10]:
df_facilities = df_facilities.reset_index()
s = df_facilities.CMS_ProvNum.value_counts()
dupNamesList = list(s.where((s > 1) & (s < 100)).dropna().keys())

In [11]:
s = df_facilities.CMS_ProvNum.value_counts()
dupNamesList = list(s.where((s > 1) & (s < 100)).dropna().keys())

In [12]:
dupFacNames_df = df_facilities[df_facilities['CMS_ProvNum'].isin(dupNamesList)].sort_values(by='CMS_ProvNum')
dupFacNames_df.to_csv('IL_dup_fac_names.csv')
dupFacNames_df

,County,FacilityName2,CMS_ProvNum,ReportingDate,confirmed_cases,deaths,CFR,outbreaks,Closed_Outbreaks,Open_Outbreaks,facilities
786,Kane,The Grove Fox Valley,145006,2021-01-22,169,24,0.142012,2,1,1,1
788,Kane,The Grove of Fox Valley,145006,2021-01-22,7,0,0.000000,1,1,0,1
798,Kankakee,Citadel Care Center of Kankakee,145043,2021-01-22,5,0,0.000000,1,0,1,1
799,Kankakee,Citadel of Kankakee,145043,2021-01-22,83,2,0.024096,1,0,1,1
1073,McHenry,Cross Roads Care Center,145222,2021-01-22,71,13,0.183099,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...
332,Cook,Little Sisters of the Poor/St. Marys Home,146185,2021-01-22,61,13,0.213115,1,1,0,1
729,Kane,Alden Estates Courts of Huntley,146186,2021-01-22,9,0,0.000000,1,1,0,1
730,Kane,Alden Estates-Courts of Huntley,146186,2021-01-22,48,2,0.041667,1,0,1,1
1185,Peoria,Sharon Healthcare Willows,14E888,2021-01-22,138,7,0.050725,1,0,1,1
1186,Peoria,Sharon Healthcare Willows South,14E888,2021-01-22,4,1,0.250000,1,1,0,1

# Convert Facility Sheet to CTP format

In [13]:
CTP_cols = ['ReportingDate', 'State', 'County', 
            'City',
            'FacilityName', 'TYPE',
            'CTP Facility Categorization',
            'State/Fed Regulated',
            'State Facility ID',
            'CMS Facility ID',
            'Date outbreak opened', 'Date outreak closed', 'Outbreak Status','Resident Census',
            
'TOTAL RESIDENT CASES', # 'Resident Positives ',
          'TOTAL Resident Probable Positives',
'TOTAL RESIDENT DEATHS', # 'Resident Deaths',
         'TOTAL Resident Probable Deaths',
'TOTAL STAFF CASES', #'Staff Positive',
         'TOTAL Staff Probable Positives',
'TOTAL STAFF DEATHS', #'TOTAL Staff Deaths',
         'TOTAL Staff Probable Deaths',
 'confirmed_cases',
 'TOTAL Resident/Staff Probable Positives',
 'deaths',
 'TOTAL Resident/Staff Probable Deaths',
 
'NEW RESIDENT CASES', #            'Resident Positives',
     'NEW Resident Probable Positives',
 'NEW RESIDENT DEATHS',
     'NEW Resident Probable Deaths',
 'NEW STAFF CASES',
     'NEW Staff Probable Positives',
 'NEW STAFF DEATHS',
     'NEW Staff Probable Deaths',
 'NEW Resident/Staff Positives',
 'NEW Resident/Staff Probable Positives',
 'NEW Resident/Staff Deaths',
 'NEW Resident/Staff Probable Deaths',
 'Residents Tested',
 'Staff Tested',
 'Personal Protective Equipment',
           'COMPLIANCE']

CTP_Blank_Cols = ['City',
             'TYPE',
            'CTP Facility Categorization',
            'State/Fed Regulated',
            'State Facility ID',
            'CMS Facility ID',
            'Date outbreak opened', 'Date outreak closed', 'Resident Census',
            
'TOTAL RESIDENT CASES', # 'Resident Positives ',
          'TOTAL Resident Probable Positives',
'TOTAL RESIDENT DEATHS', # 'Resident Deaths',
         'TOTAL Resident Probable Deaths',
'TOTAL STAFF CASES', #'Staff Positive',
         'TOTAL Staff Probable Positives',
'TOTAL STAFF DEATHS', #'TOTAL Staff Deaths',
         'TOTAL Staff Probable Deaths',

 'TOTAL Resident/Staff Probable Positives',

 'TOTAL Resident/Staff Probable Deaths',
 
'NEW RESIDENT CASES', #            'Resident Positives',
     'NEW Resident Probable Positives',
 'NEW RESIDENT DEATHS',
     'NEW Resident Probable Deaths',
 'NEW STAFF CASES',
     'NEW Staff Probable Positives',
 'NEW STAFF DEATHS',
     'NEW Staff Probable Deaths',
 'NEW Resident/Staff Positives',
 'NEW Resident/Staff Probable Positives',
 'NEW Resident/Staff Deaths',
 'NEW Resident/Staff Probable Deaths',
 'Residents Tested',
 'Staff Tested',
 'Personal Protective Equipment',
           'COMPLIANCE']

In [14]:
def open_closed(outbreaks):
    if outbreaks == 0:
        return 'Closed'
    else:
        return 'Open'
        
for col in CTP_Blank_Cols:
    df_facilities[col] = ''
df_facilities['Outbreak Status'] = df_facilities['Open_Outbreaks'].apply(open_closed) #TO FINISH
df_facilities['State'] = 'IL'
df_facilities['ReportingDate'] = reporting_date.replace('-', '')

In [15]:
df_facilities.rename(columns={'FacilityName2': 'FacilityName'}, inplace=True)
df_facilities[CTP_cols].to_csv('Reporting_data/IL_' + reporting_date + '_Facilities_LTC_data_vCTP.csv', index=False)

In [16]:
df_facilities.head()

,County,FacilityName,CMS_ProvNum,ReportingDate,confirmed_cases,deaths,CFR,outbreaks,Closed_Outbreaks,Open_Outbreaks,facilities,City,TYPE,CTP Facility Categorization,State/Fed Regulated,State Facility ID,CMS Facility ID,Date outbreak opened,Date outreak closed,Resident Census,TOTAL RESIDENT CASES,TOTAL Resident Probable Positives,TOTAL RESIDENT DEATHS,TOTAL Resident Probable Deaths,TOTAL STAFF CASES,TOTAL Staff Probable Positives,TOTAL STAFF DEATHS,TOTAL Staff Probable Deaths,TOTAL Resident/Staff Probable Positives,TOTAL Resident/Staff Probable Deaths,NEW RESIDENT CASES,NEW Resident Probable Positives,NEW RESIDENT DEATHS,NEW Resident Probable Deaths,NEW STAFF CASES,NEW Staff Probable Positives,NEW STAFF DEATHS,NEW Staff Probable Deaths,NEW Resident/Staff Positives,NEW Resident/Staff Probable Positives,NEW Resident/Staff Deaths,NEW Resident/Staff Probable Deaths,Residents Tested,Staff Tested,Personal Protective Equipment,COMPLIANCE,Outbreak Status,State
0,Adams,Adams Pointe Senior Living,No Match,20210122,4,0,0.000000,1,1,0,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Closed,IL
1,Adams,Bickford Cottage,No Match,20210122,8,0,0.000000,1,0,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Open,IL
2,Adams,Blessing Hospital SNU,No Match,20210122,6,1,0.166667,1,0,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Open,IL
3,Adams,Bradford Villa,No Match,20210122,21,2,0.095238,2,1,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Open,IL
4,Adams,Cedarhurst,No Match,20210122,26,1,0.038462,1,1,0,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Closed,IL

# Play Area

In [17]:
df = pd.DataFrame(ltc_data['LTC_Historical_Reported_Cases'])
df.sort_values(by=['reported_date'], inplace=True)
df['new_deaths']= df.deaths.diff()
df['new_confirmed_cases'] = df.confirmed_cases.diff()

In [18]:
chart_title = 'IL Cases by Week'
chart1 = alt.Chart(df).mark_bar().encode(
                     x=alt.X('yearmonthdate(reported_date):O', title='date', axis=alt.Axis(labelSeparation=10)),
                     y='new_confirmed_cases',
                     ).properties( width=400, height=400, title=chart_title)
chart_title = 'IL Deaths by Week'
chart2 = alt.Chart(df).mark_bar().encode(
                     x=alt.X('yearmonthdate(reported_date):O', title='date', axis=alt.Axis(labelSeparation=10)),
                     y='new_deaths',
                     ).properties( width=400, height=400, title=chart_title)
chart1 | chart2

alt.HConcatChart(...)