In [3]:
import pandas as pd
import urllib3 as urllib
import json
from fuzzywuzzy import process
import IPython.display

In [4]:
cms_data = pd.read_csv('/home/steve/Downloads/COVID-19_Nursing_Home_Dataset (2).csv', parse_dates=['Week Ending'])
max_date = cms_data['Week Ending'].max()
reporting_date = str(max_date)[0:10]
max_date

/home/steve/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Timestamp('2020-11-01 00:00:00')

In [5]:
cms_data[cms_data['Week Ending'] == max_date].groupby(['Provider State'])['Week Ending'].count()

Provider State
AK      20
AL     228
AR     224
AZ     145
CA    1187
CO     225
CT     212
DC      19
DE      46
FL     701
GA     357
GU       1
HI      43
IA     431
ID      82
IL     713
IN     534
KS     327
KY     285
LA     277
MA     373
MD     226
ME      93
MI     438
MN     367
MO     521
MS     204
MT      70
NC     427
ND      80
NE     196
NH      74
NJ     363
NM      70
NV      66
NY     617
OH     953
OK     298
OR     129
PA     690
PR       6
RI      79
SC     189
SD     104
TN     316
TX    1212
UT      97
VA     286
VT      35
WA     202
WI     353
WV     122
WY      36
Name: Week Ending, dtype: int64

In [6]:
MI_cms_data = cms_data[(cms_data['Provider State'] == 'MI') & (cms_data['Week Ending'] == max_date)].copy()
MI_cms_data.to_csv('./Reporting_data/MI_CMS_Data_' + str(max_date)[0:10] + '.csv')
IL_cms_data = cms_data[(cms_data['Provider State'] == 'IL') & (cms_data['Week Ending'] == max_date)].copy()
IL_cms_data.to_csv('./Reporting_data/IL_CMS_Data_' + str(max_date)[0:10] + '.csv')
max_date

Timestamp('2020-11-01 00:00:00')

In [7]:
IL_cms_data['Provider Name'] = IL_cms_data['Provider Name'].apply(lambda x: x.strip().replace('  ', ' ').upper())
#IL_cms_data.set_index(['County', 'Provider Name'], inplace = True)
IL_cms_data.sort_values(by=['County', 'Provider Name'], inplace=True)
IL_cms_data.head(5)

,Week Ending,Federal Provider Number,Provider Name,Provider Address,Provider City,Provider State,Provider Zip Code,Submitted Data,Passed Quality Assurance Check,Residents Weekly Admissions COVID-19,...,Number of Ventilators in Use for COVID-19,Any Current Supply of Ventilator Supplies,One-Week Supply of Ventilator Supplies,"Total Resident Confirmed COVID-19 Cases Per 1,000 Residents","Total Resident COVID-19 Deaths Per 1,000 Residents",Total Residents COVID-19 Deaths as a Percentage of Confirmed COVID-19 Cases,County,Three or More Confirmed COVID-19 Cases This Week,Initial Confirmed COVID-19 Case This Week,Geolocation
75382,2020-11-01,145643,BLESSING HOSPITAL SNU,BROADWAY AT 11TH STREET,QUINCY,IL,62301,Y,Y,0.0,...,NaN,NaN,NaN,0.0,0.0,NaN,Adams,N,N,NaN
81116,2020-11-01,146111,GOLDEN GOOD SHEPHERD HOME,101 PRAIRIE MILLS ROAD,GOLDEN,IL,62339,Y,Y,0.0,...,NaN,NaN,NaN,1130.4,260.9,23.1,Adams,N,N,POINT (-91.027102 40.1066)
85860,2020-11-01,145773,GOOD SAMARITAN HOME,2130 HARRISON STREET,QUINCY,IL,62301,Y,Y,0.0,...,NaN,NaN,NaN,18.0,0.0,0.0,Adams,N,N,POINT (-91.380324 39.913547)
69970,2020-11-01,145457,ST VINCENT'S HOME,1440 NORTH 10TH STREET,QUINCY,IL,62301,Y,Y,1.0,...,NaN,NaN,NaN,1098.0,98.0,8.9,Adams,Y,N,POINT (-91.400139 39.948897)
80801,2020-11-01,145800,SUNSET HOME,418 WASHINGTON STREET,QUINCY,IL,62301,Y,Y,0.0,...,NaN,NaN,NaN,36.0,0.0,0.0,Adams,N,N,POINT (-91.409341 39.92265)

In [8]:
MI_cms_data['Provider Name'] = MI_cms_data['Provider Name'].apply(lambda x: x.strip().replace('  ', ' ').upper())
#IL_cms_data.set_index(['County', 'Provider Name'], inplace = True)
MI_cms_data.sort_values(by=['County', 'Provider Name'], inplace=True)
MI_cms_data.head(5)

,Week Ending,Federal Provider Number,Provider Name,Provider Address,Provider City,Provider State,Provider Zip Code,Submitted Data,Passed Quality Assurance Check,Residents Weekly Admissions COVID-19,...,Number of Ventilators in Use for COVID-19,Any Current Supply of Ventilator Supplies,One-Week Supply of Ventilator Supplies,"Total Resident Confirmed COVID-19 Cases Per 1,000 Residents","Total Resident COVID-19 Deaths Per 1,000 Residents",Total Residents COVID-19 Deaths as a Percentage of Confirmed COVID-19 Cases,County,Three or More Confirmed COVID-19 Cases This Week,Initial Confirmed COVID-19 Case This Week,Geolocation
166746,2020-11-01,235628,JAMIESON NURSING HOME,"790 S US HWY 23, BOX 369",HARRISVILLE,MI,48740,Y,Y,0.0,...,NaN,NaN,NaN,0.0,0.0,NaN,Alcona,N,N,POINT (-83.307198 44.636688)
154984,2020-11-01,235543,LINCOLN HAVEN NURSING & REHAB COMMUNITY,950 BARLOW RD,LINCOLN,MI,48742,Y,Y,0.0,...,NaN,NaN,NaN,0.0,0.0,NaN,Alcona,N,N,POINT (-83.403334 44.683408)
153508,2020-11-01,235410,MEDILODGE OF MUNISING,300 W CITY PARK DR,MUNISING,MI,49862,Y,Y,0.0,...,NaN,NaN,NaN,0.0,0.0,NaN,Alger,N,N,POINT (-86.65692100000001 46.413498)
147299,2020-11-01,235213,ALLEGAN COUNTY MEDICAL CARE FA,3265 122ND AVE R2,ALLEGAN,MI,49010,Y,Y,0.0,...,NaN,NaN,NaN,0.0,0.0,NaN,Allegan,N,N,POINT (-85.867031 42.57891)
156320,2020-11-01,235264,ELY MANOR,1200 ELY ST,ALLEGAN,MI,49010,Y,Y,0.0,...,NaN,NaN,NaN,0.0,0.0,NaN,Allegan,N,N,POINT (-85.867585 42.515976)

# Process IL State Data

In [8]:
f = './Reporting_data/IL_2020-11-13_Facilities_LTC_data_v2.csv'
IL_state_data = pd.read_csv(f,  parse_dates=['ReportingDate'], infer_datetime_format=True) 
IL_state_data['FacilityName'] = IL_state_data['FacilityName'].apply(lambda x: x.strip().replace('  ', ' ').upper())
IL_state_data.rename(columns={'FacilityName': 'Provider Name'}, inplace=True)
IL_state_data.sort_values(by=['County', 'Provider Name'], inplace=True)

In [9]:
cols=['County', 'Provider Name', 'VLOOKUP', 'Change Score']
IL_state_data['VLOOKUP'] = '' # For Spreadsheet
IL_state_data['Change Score'] = '' # For Spreadsheet
for county in list(IL_cms_data['County'].unique()):
    #print(county)
    # Get lists of Facilities for the counties
    df_state = IL_state_data[IL_state_data['County'] == county]
    df_cms = IL_cms_data[IL_cms_data['County'] == county]
    state_facs = list(df_state['Provider Name'])
    cms_facs = list(df_cms['Provider Name'])
    for str2Match in state_facs:
        try:
            Ratios = process.extract(str2Match,cms_facs, limit=2)
            IL_state_data.loc[(IL_state_data['County'] == county) & (IL_state_data['Provider Name'] == str2Match), 'VLOOKUP'] = Ratios[0][0]            
            IL_state_data.loc[(IL_state_data['County'] == county) & (IL_state_data['Provider Name'] == str2Match), 'Change Score'] = Ratios[0][1]
        except:
            pass

IL_state_data['Change Score'].value_counts()
# str2Match = cms_facs[0]
# strOptions = state_facs

# # Pass 1 Remove Exact Matches
# for str2Match in cms_facs:
#     Ratios = process.extract(str2Match,strOptions, limit=3)
#     print(str2Match, Ratios)

86     340
100    224
95     111
90     104
45      28
      ...
30       1
63       1
99       1
75       1
16       1
Name: Change Score, Length: 69, dtype: int64

In [10]:
display(IL_state_data['Change Score'].value_counts())
#display(IL_cms_data['VLOOKUP'].value_counts())
IL_state_data.to_csv('./Reporting_data/IL_State_to_CMS_Data_' + str(max_date)[0:10] + '.csv', index=False)
IL_state_data.head(10)[cols]

86     340
100    224
95     111
90     104
45      28
      ...
30       1
63       1
99       1
75       1
16       1
Name: Change Score, Length: 69, dtype: int64

,County,Provider Name,VLOOKUP,Change Score
955,Adams,ADAMS POINTE SENIOR LIVING,BLESSING HOSPITAL SNU,45
764,Adams,BRADFORD VILLA,TIMBER POINT HEALTHCARE CENTER,32
606,Adams,CEDARHURST,SUNSET HOME,36
1026,Adams,CHADDOCK,GOLDEN GOOD SHEPHERD HOME,34
271,Adams,GOLDEN GOOD SHEPPERD HOME,GOLDEN GOOD SHEPHERD HOME,96
632,Adams,GOOD SAMARITAN HOME,GOOD SAMARITAN HOME,100
122,Adams,ILLINOIS VETERANS HOME,SUNSET HOME,86
996,Adams,SENIOR CENTER,TIMBER POINT HEALTHCARE CENTER,86
366,Adams,ST VINCENTS NURSING HOME,SUNSET HOME,86
696,Adams,SUNSET HOME,SUNSET HOME,100

# Process MI State Data

In [22]:
f = './Reporting_data/MI_11-09-2020LTC_data.csv'
MI_state_data = pd.read_csv(f,  parse_dates=['ReportingDate'], infer_datetime_format=True) 
MI_state_data.rename(columns={'FACILITY NAME': 'Provider Name', 'COUNTY': 'County'}, inplace=True)
MI_state_data['Provider Name'] = MI_state_data['Provider Name'].apply(lambda x: x.strip().replace('  ', ' ').upper())
MI_state_data.sort_values(by=['County', 'Provider Name'], inplace=True)

,ReportingDate,Provider Name,County,TYPE,NEW RESIDENT CASES,TOTAL RESIDENT CASES,NEW RESIDENT DEATHS,TOTAL RESIDENT DEATHS,NEW STAFF CASES,TOTAL STAFF CASES,NEW STAFF DEATHS,TOTAL STAFF DEATHS,Reporting
104,2020-11-09,JAMIESON NURSING HOME,ALCONA,SNF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Yes
105,2020-11-09,LINCOLN HAVEN NURSING & REHAB. COMMUNITY,ALCONA,SNF,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,Yes
106,2020-11-09,MEDILODGE OF MUNISING,ALGER,SNF,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Yes
107,2020-11-09,ALLEGAN COUNTY MEDICAL CARE COMMUNITY,ALLEGAN,SNF,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,Yes
732,2020-11-09,BEACON HOME AT THE OAKS,ALLEGAN,AFC,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,Yes
108,2020-11-09,BRIARWOOD ASSISTED LIVING,ALLEGAN,HFA,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Yes
733,2020-11-09,COUNTRY LIV - INN INC,ALLEGAN,AFC,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,Yes
63,2020-11-09,ELY MANOR NURSING & REHAB,ALLEGAN,SNF,1.0,1.0,0.0,0.0,2.0,3.0,0.0,0.0,Yes
734,2020-11-09,GOLDEN ORCHARDS I,ALLEGAN,AFC,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,Yes
735,2020-11-09,GOLDEN ORCHARDS II,ALLEGAN,AFC,NaN,0.0,NaN,0.0,NaN,0.0,NaN,0.0,Yes

In [48]:
cols=['County', 'Provider Name', 'VLOOKUP', 'Change Score']
MI_state_data['VLOOKUP'] = '' # For Spreadsheet
MI_state_data['Change Score'] = '' # For Spreadsheet
for county in list(MI_cms_data['County'].unique()):
    #print(county)
    # Get lists of Facilities for the counties
    df_state = MI_state_data[MI_state_data['County'] == county.upper()]
    df_cms = MI_cms_data[MI_cms_data['County'] == county]
    state_facs = list(df_state['Provider Name'])
    cms_facs = list(df_cms['Provider Name'])
    for str2Match in state_facs:
        try:
            Ratios = process.extract(str2Match,cms_facs, limit=2)
            #print(Ratios)
            MI_state_data.loc[(MI_state_data['County'] == county.upper()) & (MI_state_data['Provider Name'] == str2Match), 'VLOOKUP'] = Ratios[0][0]            
            MI_state_data.loc[(MI_state_data['County'] == county.upper()) & (MI_state_data['Provider Name'] == str2Match), 'Change Score'] = Ratios[0][1]
        except:
            pass

MI_state_data['Change Score'].value_counts()
# str2Match = cms_facs[0]
# strOptions = state_facs

# # Pass 1 Remove Exact Matches
# for str2Match in cms_facs:
#     Ratios = process.extract(str2Match,strOptions, limit=3)
#     print(str2Match, Ratios)

86     368
100    254
95      59
40      58
45      40
      ...
93       1
69       1
29       1
28       1
99       1
Name: Change Score, Length: 72, dtype: int64

In [49]:
# MI_cms_data[MI_cms_data['County'] == 'ALLEGAN']
# MI_cms_data['County'].unique()
# MI_state_data['County'].unique()

In [50]:
display(MI_state_data['Change Score'].value_counts())
#display(MI_cms_data['VLOOKUP'].value_counts())
MI_state_data.to_csv('./Reporting_data/MI_State_to_CMS_Data_' + str(max_date)[0:10] + '.csv', index=False)
MI_state_data.head(20)[cols]

86     368
100    254
95      59
40      58
45      40
      ...
93       1
69       1
29       1
28       1
99       1
Name: Change Score, Length: 72, dtype: int64

,County,Provider Name,VLOOKUP,Change Score
104,ALCONA,JAMIESON NURSING HOME,JAMIESON NURSING HOME,100
105,ALCONA,LINCOLN HAVEN NURSING & REHAB. COMMUNITY,LINCOLN HAVEN NURSING & REHAB COMMUNITY,99
106,ALGER,MEDILODGE OF MUNISING,MEDILODGE OF MUNISING,100
107,ALLEGAN,ALLEGAN COUNTY MEDICAL CARE COMMUNITY,ALLEGAN COUNTY MEDICAL CARE FA,90
732,ALLEGAN,BEACON HOME AT THE OAKS,ALLEGAN COUNTY MEDICAL CARE FA,49
108,ALLEGAN,BRIARWOOD ASSISTED LIVING,ELY MANOR,38
733,ALLEGAN,COUNTRY LIV - INN INC,LIFE CARE CENTER OF PLAINWELL,40
63,ALLEGAN,ELY MANOR NURSING & REHAB,ELY MANOR,90
734,ALLEGAN,GOLDEN ORCHARDS I,ELY MANOR,40
735,ALLEGAN,GOLDEN ORCHARDS II,ELY MANOR,40
109,ALLEGAN,GRACE OF DOUGLAS,GRACE OF DOUGLAS,100
736,ALLEGAN,GREEN ACRES OF WAYLAND,GRACE OF DOUGLAS,58
737,ALLEGAN,GREEN ACRES OF WAYLAND II,GRACE OF DOUGLAS,86
110,ALLEGAN,HARBORS HEALTH FACILITY,ELY MANOR,48
111,ALLEGAN,LAKESIDE VISTA AMSTERDAM HAUS,ALLEGAN COUNTY MEDICAL CARE FA,39
112,ALLEGAN,LAKESIDE VISTA DELPH HAUS,LAURELS OF SANDY CREEK (THE),42
113,ALLEGAN,LAKESIDE VISTA FRIESLAND HAUS,LAURELS OF SANDY CREEK (THE),43
114,ALLEGAN,LAKESIDE VISTA ROTTERDAM HAUS,LAURELS OF SANDY CREEK (THE),43
115,ALLEGAN,LAKESIDE VISTA ZEELAND HAUS,LAURELS OF SANDY CREEK (THE),44
508,ALLEGAN,LAURELS OF SANDY CREEK,LAURELS OF SANDY CREEK (THE),95

# Play Area

In [ ]:
# V1 - DO NOT USE
# DO NOT USE - DO NOT USE - DO NOT USE - DO NOT USE - DO NOT USE - DO NOT USE - DO NOT USE - DO NOT USE - DO NOT USE - DO NOT USE - DO NOT USE

# cols=['County', 'Provider Name', 'VLOOKUP', 'Changed']
# IL_state_data['VLOOKUP'] = '' # For Spreadsheet
# IL_state_data['Change Score'] = '' # For Spreadsheet
# for county in list(IL_cms_data['County'].unique()):
#     #print(county)
#     # Get lists of Facilities for the counties
#     df_state = IL_state_data[IL_state_data['County'] == county]
#     df_cms = IL_cms_data[IL_cms_data['County'] == county]
#     state_facs = list(df_state['Provider Name'])
#     cms_facs = list(df_cms['Provider Name'])
#     for str2Match in state_facs:
#         try:
#             Ratios = process.extract(str2Match,cms_facs, limit=2)
#             if (Ratios[0][1] == 100):
#                 match_val = 'EXACT MATCH'
#             else:
#                 match_val = 'Difference: ' + str(Ratios[0][1])   
#             if (Ratios[0][1] > 90):
#                 IL_state_data.loc[(IL_state_data['County'] == county) & (IL_state_data['Provider Name'] == str2Match), 'VLOOKUP'] = Ratios[0][0]            
# #                 print(str2Match, Ratios, match_val)
#                 IL_state_data.loc[(IL_state_data['County'] == county) & (IL_state_data['Provider Name'] == str2Match), 'Changed'] = match_val 
#         except:
#             pass

# IL_state_data['Changed'].value_counts()

In [5]:
key = 2
print(IL_cms_data['Provider Name'].iloc[key])
print(IL_cms_data['Provider Name'].iloc[key].strip())
print(IL_cms_data['Provider Name'].iloc[key].strip().replace('  ', ' '))
print(IL_cms_data['Provider Name'].iloc[key].strip())

SERENITY OF LAKE STOREY
SERENITY OF LAKE STOREY
SERENITY OF LAKE STOREY
SERENITY OF LAKE STOREY

In [ ]:
str2Match = cms_facs[0]
strOptions = state_facs

# Pass 1 Remove Exact Matches
for str2Match in cms_facs:
    if str2Match in strOptions:
        print (str2Match, 'Match Exact')

In [ ]:
df_state = IL_state_data[IL_state_data['County'] == 'Adams']
df_cms = IL_cms_data[IL_cms_data['County'] == 'Adams']
state_facs = list(df_state['Provider Name'])
cms_facs = list(df_cms['Provider Name'])

In [ ]:
str2Match = cms_facs[0]
strOptions = state_facs

# Pass 1 Remove Exact Matches
for str2Match in cms_facs:
    Ratios = process.extract(str2Match,strOptions, limit=3)
    print(str2Match, Ratios)

In [ ]:
Ratios[0][1]

In [ ]:
process.extract?

In [ ]:
IL_state_data[IL_state_data['County'] == 'Adams']

In [ ]:
cols = ['Week Ending', 'County', 'Provider Name',
       'Residents Weekly Admissions COVID-19',
       'Residents Total Admissions COVID-19',
       'Residents Weekly Confirmed COVID-19',
       'Residents Total Confirmed COVID-19',
       'Residents Weekly Suspected COVID-19',
       'Residents Total Suspected COVID-19', 'Residents Weekly All Deaths',
       'Residents Total All Deaths', 'Residents Weekly COVID-19 Deaths',
       'Residents Total COVID-19 Deaths',
       'Staff Weekly Confirmed COVID-19',
 'Staff Total Confirmed COVID-19',
 'Staff Weekly Suspected COVID-19',
 'Staff Total Suspected COVID-19',
 'Staff Weekly COVID-19 Deaths',
 'Staff Total COVID-19 Deaths',]
display(IL_cms_data[IL_cms_data['County'] == 'Adams'][cols])
cms_data[cms_data['Week Ending'] == max_date].groupby(['Provider State'])[cols].sum().to_csv('cms_state_totals_' + reporting_date + '.csv')
cms_data.groupby(['Provider State', 'Week Ending'])[cols].sum().to_csv('cms_state_totals_up_to_' + reporting_date + '.csv')

#list(cms_data.columns)
#[s for s in list(cms_data.columns) if "Staff" in s]

In [ ]:
reporting_date = str(max_date)[0:10]
reporting_date

In [ ]:
#IL_state_data.join(IL_cms_data, how='left').head(50)
pd.merge(IL_cms_data, IL_state_data,  how='left', on=['County','Provider Name']).to_csv('IL_CMS_to_state.csv')
pd.merge(IL_cms_data, IL_state_data,  how='right', on=['County','Provider Name']).to_csv('IL_state_to_CMS.csv')

In [ ]:
pd.merge(IL_cms_data, IL_state_data,  how='inner', on=['County','Provider Name']).to_csv("IL_in_both.csv")
pd.merge(IL_cms_data, IL_state_data,  how='outer', on=['County','Provider Name']).to_csv("IL_NOT_in_both.csv")

In [ ]:
len(IL_cms_data)

In [ ]:
len(IL_state_data)

In [ ]:
count = "Adams"
print(IL_cms_data['County'].value_counts())
print(IL_state_data['County'].value_counts())

In [ ]:
# for county in IL_cms_data['County'].unique():
#     print(county)
county='Adams'
matches = 0
non_matches = 0
for row in IL_cms_data[IL_cms_data['County'] == county].iterrows():
  #  print(row[1]['County'], row[1]['Provider Name'])
    state_row = IL_state_data[(IL_state_data['County'] == row[1]['County']) & (IL_state_data['Provider Name'] ==row[1]['Provider Name'])]

    if len(state_row == 1):
        print('\n')
        print(row[1]['County'], row[1]['Provider Name'], "************* Match ******************")
        matches += 1
        print("\n" + str(state_row))
    else:
        print('\n')
        print(row[1]['County'], row[1]['Provider Name'], "No Match")
        print(state_row)
        non_matches += 1
print(matches, non_matches)

In [ ]:
IL_state_data[(IL_state_data['County'] == 'Cook') & (IL_state_data['Provider Name'] == 'FRIENDSHIP VILLAGE LTC')]

In [ ]:
IL_state_data.head(5)

In [ ]:
IL_cms_data[IL_cms_data['County'] == county]